/** @type {import('tailwindcss').Config} */
// Tokens ported from design/the_arcane_grimoire/DESIGN.md and the mockup configs.
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'bg-page': '#0c0b14',
        'bg-panel': '#0e0d16',
        'bg-surface': '#16142b',
        surface: '#13121c',
        'surface-container-lowest': '#0e0d16',
        'surface-container-low': '#1c1a24',
        'surface-container': '#201e28',
        'surface-container-high': '#2a2933',
        'surface-container-highest': '#35333e',
        'surface-variant': '#35333e',
        'surface-bright': '#3a3842',
        'border-default': '#29263f',
        'border-subtle': '#1d1a2e',
        outline: '#969083',
        'outline-variant': '#4b463b',
        'on-surface': '#e5e0ee',
        'on-surface-variant': '#cdc6b7',
        'on-background': '#e5e0ee',
        'text-muted': '#9b96b8',
        'text-tertiary': '#6b6789',
        primary: '#ffefc0',
        'primary-container': '#e3d3a0',
        'on-primary': '#39300b',
        'on-primary-container': '#665a32',
        secondary: '#eec054',
        'surface-tint': '#d5c694',
        error: '#ffb4ab',
        'rune-quest': '#d4a93f',
        'rune-tome': '#5b8dd9',
        'rune-chronicle': '#d98b4a',
        'rune-entity': '#9d6bd9',
        'status-error': '#ff4d4d',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        base: '8px',
        sm: '12px',
        md: '24px',
        lg: '40px',
        xl: '64px',
        gutter: '24px',
        margin: '32px',
      },
      fontFamily: {
        'display-lg': ['Cinzel', 'serif'],
        'headline-lg': ['Cinzel', 'serif'],
        'headline-md': ['Cinzel', 'serif'],
        'headline-sm': ['Cinzel', 'serif'],
        'headline-lg-mobile': ['Cinzel', 'serif'],
        'body-lg': ['Spectral', 'serif'],
        'body-md': ['Spectral', 'serif'],
        'body-sm': ['Spectral', 'serif'],
        'label-md': ['Spectral', 'serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '0.05em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '500' }],
        'headline-sm': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '300' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
